name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: prnvvv
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snake.svg to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          release_name: Latest Snake Animation
          files: dist/snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify via Discord
        uses: Ilshidur/action-discord@v2
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: "New snake animation generated! Check it out: https://raw.githubusercontent.com/prnvvv/prnvvv/output/snake.svg"
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}