name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at 00:00 UTC
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: prnvvv
          outputs: |
            snake.svg
            snake-dark.svg?palette=github-dark
            snake-light.svg?palette=github-light

      - name: Commit & Push snake
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add snake.svg
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
