name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # Add permissions block
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: prnvvv
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          snake_color: '#2E9EF7'
          commit_message: "Generate snake animation"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  display:
    runs-on: ubuntu-latest
    steps:
      - name: Display Snake
        run: |
          echo '<div align="center">' >> README.md
          echo '  <picture>' >> README.md
          echo '    <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/prnvvv/prnvvv/output/github-contribution-grid-snake-dark.svg">' >> README.md
          echo '    <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/prnvvv/prnvvv/output/github-contribution-grid-snake.svg">' >> README.md
          echo '    <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/prnvvv/prnvvv/output/github-contribution-grid-snake.svg">' >> README.md
          echo '  </picture>' >> README.md
          echo '</div>' >> README.md
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "docs: update snake display"
          git push
